spring:
  redis:
    database: 1
    host: 127.0.0.1
  application:
    name: y-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/y_pan?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: org.xu.pan
  title: y-pan-server docs
  description: y-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: stan
  contact-url: https://github.com/Qingchao-Xu
  contact-email: 15154739019@163.com
  version: 1.0

logging:
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO

