spring:
  redis:
    database: 1
    host: 127.0.0.1
  application:
    name: y-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/y_pan?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        deleteFileInput:
          destination: deleteFileTopic
          group: deleteFileGroup
        fileRestoreInput:
          destination: fileRestoreTopic
          group: fileRestoreGroup
        physicalDeleteFileInput:
          destination: physicalDeleteFileTopic
          group: physicalDeleteFileGroup
        userSearchInput:
          destination: userSearchTopic
          group: userSearchGroup
        errorLogInput:
          destination: errorLogTopic
          group: errorLogGroup
        deleteFileOutput:
          destination: deleteFileTopic
        fileRestoreOutput:
          destination: fileRestoreTopic
        physicalDeleteFileOutput:
          destination: physicalDeleteFileTopic
        userSearchOutput:
          destination: userSearchTopic
        errorLogOutput:
          destination: errorLogTopic



mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: org.xu.pan
  title: y-pan-server docs
  description: y-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: stan
  contact-url: https://github.com/Qingchao-Xu
  contact-email: 15154739019@163.com
  version: 1.0

logging:
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO

org:
  xu:
    pan:
      storage:
        engine:
          oss:
            bucket-name: y-pan-test-1
            endpoint: oss-cn-beijing.aliyuncs.com
            access-key-id:
            access-key-secret:
            auto-create-bucket: true
      server:
        share-prefix: http://127.0.0.1:5173/
      bloom:
        filter:
          local:
            items:
              - name: SHARE_SIMPLE_DETAIL
                funnel-type-name: LONG
                expected-insertions: 10000000
                fpp: 0.01
#          fdfs:
#            connect-timeout: 600
#            tracker-list:
#              - 39.98.37.93:22122
#            group: group1